### PR TITLE
Cleanups to Geometry

### PR DESCRIPTION
**Pull request by knoepfel**
Changes as presented and approved at the November 29th LCM:

https://indico.fnal.gov/event/57355/

### CODE REVIEW

**Comment by knoepfel** [comment]
@lgarren, the complete list of PRs and feature branches required to run the CI is below.

#### LArSoft PRs

- LArSoft/larwirecell#27
- LArSoft/larana#23
- LArSoft/lareventdisplay#18
- LArSoft/larevt#20
- LArSoft/lardata#30
- LArSoft/larpandora#29
- LArSoft/larsimdnn#9
- LArSoft/larsim#106
- LArSoft/larrecodnn#36
- LArSoft/larreco#48
- LArSoft/larexamples#11
- LArSoft/lardataalg#38
- LArSoft/larcore#14
- LArSoft/larcorealg#34

#### DUNE PRs

- DUNE/duneopdet#22
- DUNE/dunesw#45
- DUNE/dunesim#28
- DUNE/dunereco#34
- DUNE/duneprototypes#19
- DUNE/dunedataprep#15
- DUNE/dunecore#42
- DUNE/duneana#20

#### SBN PRs

- DeepLearnPhysics/Supera#12  
    - *Supera is a submodule of sbncode; not sure how to incorporate this in CI*
- SBNSoftware/icaruscode#496
- SBNSoftware/icarusalg#63
- SBNSoftware/sbndcode#311
- SBNSoftware/sbncode#322

#### ArgoNeuT feature branches

- argoneutcode:feature/knoepfel_geometry_iterator_interface

#### MicroBooNE feature branches

- ubana:feature/knoepfel_geometry_iterator_interface
- ubcrt:feature/knoepfel_geometry_iterator_interface
- ubcv:feature/knoepfel_geometry_iterator_interface
- ubevt:feature/knoepfel_geometry_iterator_interface
- ublite:feature/knoepfel_geometry_iterator_interface
- ubreco:feature/knoepfel_geometry_iterator_interface
- ubsim:feature/knoepfel_geometry_iterator_interface

**Comment by lgarren** [comment]
Thanks @knoepfel

**Comment by lgarren** [comment]
trigger build with pull requests LArSoft/larcorealg#34, LArSoft/larwirecell#27, LArSoft/larana#23, LArSoft/lareventdisplay#18, LArSoft/larevt#20, LArSoft/lardata#30, LArSoft/larpandora#29, LArSoft/larsimdnn#9, LArSoft/larsim#106, LArSoft/larrecodnn#36, LArSoft/larreco#48, LArSoft/larexamples#11, LArSoft/lardataalg#38, LArSoft/larcore#14, DUNE/duneopdet#22, DUNE/dunesw#45, DUNE/dunesim#28, DUNE/dunereco#34, DUNE/duneprototypes#19, DUNE/dunedataprep#15, DUNE/dunecore#42, DUNE/duneana#20, SBNSoftware/icaruscode#496, SBNSoftware/icarusalg#63, SBNSoftware/sbndcode#311, SBNSoftware/sbncode#322, argoneutcode@feature/knoepfel_geometry_iterator_interface, ubana@feature/knoepfel_geometry_iterator_interface, ubcrt@feature/knoepfel_geometry_iterator_interface, ubcv@feature/knoepfel_geometry_iterator_interface, ubevt@feature/knoepfel_geometry_iterator_interface, ublite@feature/knoepfel_geometry_iterator_interface, ubreco@feature/knoepfel_geometry_iterator_interface, ubsim@feature/knoepfel_geometry_iterator_interface

**Comment by lgarren** [comment]
trigger build with pull requests LArSoft/larcorealg#34, LArSoft/larwirecell#27, LArSoft/larana#23, LArSoft/lareventdisplay#18, LArSoft/larevt#20, LArSoft/lardata#30, LArSoft/larpandora#29, LArSoft/larsimdnn#9, LArSoft/larsim#106, LArSoft/larrecodnn#36, LArSoft/larreco#48, LArSoft/larexamples#11, LArSoft/lardataalg#38, LArSoft/larcore#14, DUNE/duneopdet#22, DUNE/dunesw#45, DUNE/dunesim#28, DUNE/dunereco#34, DUNE/duneprototypes#19, DUNE/dunedataprep#15, DUNE/dunecore#42, DUNE/duneana#20, SBNSoftware/icaruscode#496, SBNSoftware/icarusalg#63, SBNSoftware/sbndcode#311, SBNSoftware/sbncode#322, argoneutcode@feature/knoepfel_geometry_iterator_interface, ubana@feature/knoepfel_geometry_iterator_interface, ubcrt@feature/knoepfel_geometry_iterator_interface, ubcv@feature/knoepfel_geometry_iterator_interface, ubevt@feature/knoepfel_geometry_iterator_interface, ublite@feature/knoepfel_geometry_iterator_interface, ubreco@feature/knoepfel_geometry_iterator_interface, ubsim@feature/knoepfel_geometry_iterator_interface

**Pull request merged**
