### PR TITLE
More of the same for issue 25990

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
`AuxDetGeometry` turn.

### CODE REVIEW

**Comment by tomjunk** [comment]
Looks cut-and-pasted from PR #18, but without the force_reload test.  So the second if below
can never invoke TGeoManager::UnlockGeometry(), and one only does do_the_right_thing if we
don't yet have a gGeoManager.  While this works, one does a double-take looking at that second if.

  if( !gGeoManager ){
      if (gGeoManager) TGeoManager::UnlockGeometry();
      else { // very first time (or so it should)
        do_the_right_thing
       ....
   }
}

**Comment by PetrilloAtWork** [comment]
Thank you, Tom. I did that change too hastily, it seems (I had noticed the difference, but hadn't drawn any conclusion out of it).

**Comment by tomjunk** [comment]
Approved

**Comment by lgarren** [comment]
The CI tests will, of course, fail but local testing confirms that this second PR resolves the gdml unit problem.

**Pull request merged**
