### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by knoepfel**
As discussed at [this LCM](https://indico.fnal.gov/event/56265/contributions/251002/attachments/160060/210660/larsoft-coordination-2022-09-20.pdf).

### CODE REVIEW

**Comment by lgarren** [comment]
argoneutcode CI is OK
https://dbweb8.fnal.gov:8443/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/7598&builds=

**Comment by lgarren** [comment]
DUNE CI: https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/14357&builds=

**Comment by lgarren** [comment]
@knoepfel ICARUS CI test failures
https://dbweb8.fnal.gov:8443/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5570&builds=

**Comment by knoepfel** [comment]
Thanks, @lgarren.  Running the ICARUS job locally—at first blush it doesn't look related to the PR.

**Comment by lgarren** [comment]
Latest round is okay:
https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10613&builds=
https://dbweb8.fnal.gov:8443/LarCI/app/ns:DUNE/view_builds/index?offset=0&builds=dune_ci/14363&builds=
https://dbweb8.fnal.gov:8443/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5584&builds=
https://dbweb8.fnal.gov:8443/LarCI/app/ns:ArgoNeuT/view_builds/index?offset=0&builds=argoneut_ci/7614&builds=

Uboone unit tests show no problems.

**Comment by lgarren** [comment]
approve

**Pull request merged**
