### PR TITLE
Bug fixes in geometry test.

### PR DESCRIPTION
**Pull request by PetrilloAtWork**

### CODE REVIEW

**Comment by lgarren** [comment]
@PetrilloAtWork  How urgent is this bug fix?

**Comment by lgarren** [comment]
trigger build

**Comment by PetrilloAtWork** [comment]
Tests of the new ICARUS geometry fail, and the new geometry is a bug fix affecting GEANT4 simulation.
So I would say: please merge it into the next release.
Is that acceptable?

**Comment by lgarren** [comment]
Thanks @PetrilloAtWork   
Sounds as if we should get it into develop as soon as reasonable.   Unfortunately, we have to wait for the experiments to catch up with this weeks' larsoft release before we can run a useful CI test.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
The argoneut, dune, and sbnd CI tests are normal.
uboone and icarus builds fail with a version mismatch because they have not yet updated.

**Comment by lgarren** [comment]
approve

manually built unit tests for uboone and icarus are OK

**Pull request merged**
